export type FeaturedLocation = {
  id: string;
  name: string;
  region: string;
  lat: number;
  lon: number;
  kind: "city" | "landmark" | "science" | "wild";
  blurb: string;
};

export const FEATURED_LOCATIONS: FeaturedLocation[] = [
  {
    id: "nyc",
    name: "New York",
    region: "United States",
    lat: 40.7128,
    lon: -74.006,
    kind: "city",
    blurb: "The Atlantic seaboard stacked into glass and grid — still the loudest city lights on the night side.",
  },
  {
    id: "london",
    name: "London",
    region: "United Kingdom",
    lat: 51.5074,
    lon: -0.1278,
    kind: "city",
    blurb: "A river city at the hinge of Europe, older than the maps that still refuse to let it go.",
  },
  {
    id: "tokyo",
    name: "Tokyo",
    region: "Japan",
    lat: 35.6762,
    lon: 139.6503,
    kind: "city",
    blurb: "The largest metropolitan glow on Earth — a continuous city from the bay to the mountains.",
  },
  {
    id: "paris",
    name: "Paris",
    region: "France",
    lat: 48.8566,
    lon: 2.3522,
    kind: "city",
    blurb: "The Seine’s tight curve, a radial boulevard plan, and a nightscape that still reads from orbit.",
  },
  {
    id: "cairo",
    name: "Giza Plateau",
    region: "Egypt",
    lat: 29.9792,
    lon: 31.1342,
    kind: "landmark",
    blurb: "Where the Nile’s green ribbon meets the Western Desert — and four-thousand-year-old geometry still holds.",
  },
  {
    id: "dubai",
    name: "Dubai",
    region: "United Arab Emirates",
    lat: 25.2048,
    lon: 55.2708,
    kind: "city",
    blurb: "A city drawn on sand in a single generation, lit hard enough to read from the terminator.",
  },
  {
    id: "singapore",
    name: "Singapore",
    region: "Singapore",
    lat: 1.3521,
    lon: 103.8198,
    kind: "city",
    blurb: "A port-state on the Strait of Malacca, sitting on one of the planet’s busiest shipping seams.",
  },
  {
    id: "sydney",
    name: "Sydney",
    region: "Australia",
    lat: -33.8688,
    lon: 151.2093,
    kind: "city",
    blurb: "Harbour and sandstone, facing the Pacific, with a night signature that pins the Australian east coast.",
  },
  {
    id: "rio",
    name: "Rio de Janeiro",
    region: "Brazil",
    lat: -22.9068,
    lon: -43.1729,
    kind: "city",
    blurb: "Granite peaks, Guanabara Bay, and a city pressed between forest and Atlantic swell.",
  },
  {
    id: "cape-town",
    name: "Cape Town",
    region: "South Africa",
    lat: -33.9249,
    lon: 18.4241,
    kind: "city",
    blurb: "Table Mountain at the meeting of two oceans — the southern hinge of the African continent.",
  },
  {
    id: "ksc",
    name: "Kennedy Space Center",
    region: "Florida, USA",
    lat: 28.5729,
    lon: -80.649,
    kind: "science",
    blurb: "The coastal range that threw Apollo at the Moon. Pads still light up the marsh on launch nights.",
  },
  {
    id: "baikonur",
    name: "Baikonur",
    region: "Kazakhstan",
    lat: 45.965,
    lon: 63.305,
    kind: "science",
    blurb: "The oldest operating launch complex on Earth — steppe, rail, and a corridor to low orbit.",
  },
  {
    id: "everest",
    name: "Mount Everest",
    region: "Nepal / China",
    lat: 27.9881,
    lon: 86.925,
    kind: "wild",
    blurb: "The planet’s highest point, 8,849 m above the geoid — a white knot in the Himalayan chain.",
  },
  {
    id: "machu",
    name: "Machu Picchu",
    region: "Peru",
    lat: -13.1631,
    lon: -72.545,
    kind: "landmark",
    blurb: "A fifteenth-century citadel on a knife-edge ridge of the Andes, above the Urubamba loop.",
  },
  {
    id: "grand-canyon",
    name: "Grand Canyon",
    region: "Arizona, USA",
    lat: 36.1069,
    lon: -112.1129,
    kind: "wild",
    blurb: "Two billion years of rock opened by the Colorado — a wound you can still pick out from LEO.",
  },
  {
    id: "reef",
    name: "Great Barrier Reef",
    region: "Queensland, Australia",
    lat: -18.2871,
    lon: 147.6992,
    kind: "wild",
    blurb: "The largest living structure on the planet, a two-thousand-kilometre pale shallows off Queensland.",
  },
  {
    id: "reykjavik",
    name: "Reykjavík",
    region: "Iceland",
    lat: 64.1466,
    lon: -21.9426,
    kind: "city",
    blurb: "The world’s northernmost capital, sitting on a mid-ocean ridge that is still pulling apart.",
  },
  {
    id: "mcmurdo",
    name: "McMurdo Station",
    region: "Antarctica",
    lat: -77.8419,
    lon: 166.6863,
    kind: "science",
    blurb: "The logistical heart of the Antarctic program, on Ross Island under six months of night or day.",
  },
  {
    id: "mauna-kea",
    name: "Mauna Kea",
    region: "Hawaiʻi, USA",
    lat: 19.8207,
    lon: -155.4681,
    kind: "science",
    blurb: "A shield volcano that is also one of the darkest, driest observatory sites on Earth.",
  },
  {
    id: "petra",
    name: "Petra",
    region: "Jordan",
    lat: 30.3285,
    lon: 35.4444,
    kind: "landmark",
    blurb: "A Nabataean capital carved from red sandstone at the edge of Wadi Araba.",
  },
  {
    id: "venice",
    name: "Venice",
    region: "Italy",
    lat: 45.4408,
    lon: 12.3155,
    kind: "landmark",
    blurb: "A city poured into a lagoon — canals as streets, and a tide that keeps rewriting the plan.",
  },
  {
    id: "serengeti",
    name: "Serengeti",
    region: "Tanzania",
    lat: -2.3333,
    lon: 34.8333,
    kind: "wild",
    blurb: "An open savanna on the south-east of the Nile basin, still a corridor for the great migration.",
  },
];

export const KIND_LABEL: Record<FeaturedLocation["kind"], string> = {
  city: "City",
  landmark: "Landmark",
  science: "Science",
  wild: "Terrain",
};
