/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAircraftRouteImport } from './routes/api/aircraft'
import { Route as ApiFirmsRouteImport } from './routes/api/firms'
import { Route as ApiSatellitesRouteImport } from './routes/api/satellites'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAircraftRoute = ApiAircraftRouteImport.update({
  id: '/api/aircraft',
  path: '/api/aircraft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFirmsRoute = ApiFirmsRouteImport.update({
  id: '/api/firms',
  path: '/api/firms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSatellitesRoute = ApiSatellitesRouteImport.update({
  id: '/api/satellites',
  path: '/api/satellites',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/aircraft': typeof ApiAircraftRoute
  '/api/firms': typeof ApiFirmsRoute
  '/api/satellites': typeof ApiSatellitesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/aircraft': typeof ApiAircraftRoute
  '/api/firms': typeof ApiFirmsRoute
  '/api/satellites': typeof ApiSatellitesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/aircraft': typeof ApiAircraftRoute
  '/api/firms': typeof ApiFirmsRoute
  '/api/satellites': typeof ApiSatellitesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/aircraft' | '/api/firms' | '/api/satellites'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/aircraft' | '/api/firms' | '/api/satellites'
  id: '__root__' | '/' | '/api/aircraft' | '/api/firms' | '/api/satellites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAircraftRoute: typeof ApiAircraftRoute
  ApiFirmsRoute: typeof ApiFirmsRoute
  ApiSatellitesRoute: typeof ApiSatellitesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/aircraft': {
      id: '/api/aircraft'
      path: '/api/aircraft'
      fullPath: '/api/aircraft'
      preLoaderRoute: typeof ApiAircraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/firms': {
      id: '/api/firms'
      path: '/api/firms'
      fullPath: '/api/firms'
      preLoaderRoute: typeof ApiFirmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/satellites': {
      id: '/api/satellites'
      path: '/api/satellites'
      fullPath: '/api/satellites'
      preLoaderRoute: typeof ApiSatellitesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAircraftRoute: ApiAircraftRoute,
  ApiFirmsRoute: ApiFirmsRoute,
  ApiSatellitesRoute: ApiSatellitesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
